import { motion } from 'framer-motion';
import { Gavel, CheckCircle, AlertCircle, FileCheck, Scale, Info } from 'lucide-react';
import { useEffect } from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const TermsConditions = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <>
      <Navbar />
      <div className="bg-white min-h-screen pt-40 pb-24">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-indigo-50 text-accent font-bold uppercase tracking-widest text-xs mb-6 border border-indigo-100">
              <Scale size={14} /> Legal Terms
            </div>
            <h1 className="text-4xl md:text-6xl font-black text-primary mb-10 tracking-tight">
              Terms & <span className="text-gradient">Conditions</span>
            </h1>
            
            <div className="prose prose-lg max-w-none text-slate-600 space-y-8 font-light leading-relaxed">
              <section>
                <h2 className="text-2xl font-bold text-primary mb-4 flex items-center gap-3 mt-12">
                  <span className="w-10 h-10 rounded-xl bg-slate-50 flex items-center justify-center text-accent shadow-sm border border-slate-100"><Info size={20}/></span>
                  1. Acceptance of Terms
                </h2>
                <p>
                  By accessing and using this website, you agree to be bound by these Terms and Conditions. Our services are provided under the registered name DevelopersHub Corporation. If you do not agree with any part of these terms, you must refrain from using our services.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-primary mb-4 flex items-center gap-3 mt-12">
                  <span className="w-10 h-10 rounded-xl bg-slate-50 flex items-center justify-center text-accent shadow-sm border border-slate-100"><FileCheck size={20}/></span>
                  2. Intellectual Property
                </h2>
                <p>
                  All content, branding, design systems, and source code generated by DevelopersHub are protected by intellectual property laws. Users may not reproduce, distribute, or create derivative works without explicit written consent from our legal department.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-primary mb-4 flex items-center gap-3 mt-12">
                  <span className="w-10 h-10 rounded-xl bg-slate-50 flex items-center justify-center text-accent shadow-sm border border-slate-100"><CheckCircle size={20}/></span>
                  3. Service Standards
                </h2>
                <p>
                  We strive for 100% uptime and technical excellence. However, DevelopersHub does not warrant that the website or its services will be uninterrupted or error-free. We reserve the right to modify or discontinue any part of our platform without prior notice to maintain security and performance standards.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-primary mb-4 flex items-center gap-3 mt-12">
                  <span className="w-10 h-10 rounded-xl bg-slate-50 flex items-center justify-center text-accent shadow-sm border border-slate-100"><AlertCircle size={20}/></span>
                  4. Limitation of Liability
                </h2>
                <p>
                  DevelopersHub shall not be liable for any indirect, incidental, special, or consequential damages arising out of your use of our digital platform. Our total liability for any claim shall be limited to the amount paid for the specific service rendered.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-primary mb-4 flex items-center gap-3 mt-12">
                  <span className="w-10 h-10 rounded-xl bg-slate-50 flex items-center justify-center text-accent shadow-sm border border-slate-100"><Gavel size={20}/></span>
                  5. Governing Law
                </h2>
                <p>
                  These terms shall be governed by and construed in accordance with the laws of our operating jurisdiction. Any disputes relating to these terms shall be subject to the exclusive jurisdiction of the courts located in that region.
                </p>
              </section>
            </div>

            <div className="mt-20 p-8 rounded-[2rem] bg-indigo-50/30 border border-indigo-100 text-center">
              <p className="text-slate-500 font-medium italic">
                These terms are effective as of April 2026. DevelopersHub reserves the right to amend these terms at any time by posting the updated version of this page.
              </p>
            </div>
          </motion.div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default TermsConditions;
